openapi: '2.0.0'
info:
  title: RBAC CRUD
  version: '1.0'
servers:
  - url: localhost://user-service/v1
paths:
  /:
    get:
      responses:
        '200':
          description: 'User Microservice v.1.0'
  /create:
    post:
      summary: 'To register new user'
      consumes:
          - application/json
      parameters:
        - in: body
          name: User
          description: 'To register new user'
          schema:
            type: object
            required:
              - userName
            properties:
              userName:
                type: string
              firstName:
                type: string
              lastName:
                type: string

      responses:
        '200':
          description: User created
 

    